#!/bin/bash

# Copyright (c) 2013 The CoreOS Authors. All rights reserved.
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# CROS_DEBUG equals one if we've booted in developer mode or we've booted a
# developer image.
crossystem "cros_debug?1"
CROS_DEBUG=$((! $?))

# Mount stateful partition for dev packages
# TODO(arkaitzr@chromium.org) - Only use CROS_DEBUG when cros_debug is
# correctly set in a test VM after updating itself to itself (that is, it does
# not fail cros_au_test_harness).
if [ "$CROS_DEBUG" = "1" -o -f /root/.dev_mode ]; then
  # TODO(polvi): remove non -usr image stuff post conversion
  # This will fail if it is a non-usr image, but that's alright!
  mount -n -o remount,rw /usr
  # Take a stab at mounting root read-write
  mount -n -o remount,rw /
fi

# TODO(marineam): Move this to a sysctl file or delete
# Enable crash reporting for all future exec'd processes, even those that have
# gone through setuid.
echo 2 > /proc/sys/fs/suid_dumpable
