#!/bin/bash -e

# Copyright (c) 2014 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# We want to grab the GROUP variable
[ -e /usr/share/coreos/update.conf ] && source /usr/share/coreos/update.conf
[ -e /etc/coreos/update.conf ] && source /etc/coreos/update.conf

source /usr/lib/os-release

mkdir -p /run/coreos
echo -e "Core\033[38;5;206mO\033[38;5;45mS\033[39m ${GROUP} (${VERSION})" > /run/coreos/motd

if [[ -d "/etc/motd.d" ]]; then
	cat /etc/motd.d/*.conf 2>/dev/null >> /run/coreos/motd || true
fi

if ! systemctl is-active locksmithd > /dev/null; then
	echo -e "Update Strategy: \033[31mNo Reboots\033[39m" >> /run/coreos/motd
fi

systemctl list-units --state=failed --no-legend > /run/coreos/motd-failed
count=$(cat /run/coreos/motd-failed | wc -l)
if [ ${count} -ne 0 ]; then
	echo -e "Failed Units: \033[31m${count}\033[39m" >> /run/coreos/motd
	cat /run/coreos/motd-failed | awk '{ print "  " $1 }' >> /run/coreos/motd
fi
