#!/bin/bash

# Copyright (c) 2013 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

SSH_DIR=/etc/ssh
mkdir -p ${SSH_DIR}

ssh-keygen -A || echo "Failed to generate ssh keys."

# Provide key fingerprints via issue
mkdir -p /run/issue.d
for KEY_FILE in $(ls ${SSH_DIR}/ssh_host_*_key) ; do
  ssh-keygen -l -f ${KEY_FILE}
done | awk '{print "SSH host key: " $2 " " $4}' > /run/issue.d/00_ssh_host_keys
/usr/lib/coreos/issuegen
